### ISSUE TITLE
Needs recent version of node.js?  

### ISSUE THREAD

**Issue by RickAndrews** [lukaskollmer/passcard#1]
I'm using macOS 10.12.6 and I've not installed npm before.
After installing `node.js v6.11.2 LTS` and passcard, when I run `passcard` I get a syntax error
However, after installing `node.js v8.3.0 Current`, I can run `passcard` successfully

Perhaps you should mention this dependency in your readme?
PS cool idea!

**Comment by lukaskollmer** [comment]
You're right `passcard` requires node v7.6 because that's when `async`/`await` support was added. I'll update the readme
